[workspace]
members = [
    "games",
    "alphazero",
    "alphaothello_gui",
    "alphazero_train",
    "shared",
    "players",
    "main",
    "human_play"
]
default-members = ["main"]
resolver = "2"

[profile.dev]
debug = true