[package]
name = "alphazero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-pbar = "0.2.0"
dfdx = "0.13.0"
shared = { path = "../shared"}